version: "3.8"
services:
  web:
    build: .
    container_name: predictions
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/AgriTrack-Prediction
    ports:
      - "8000:8000"
